### ISSUE TITLE
beta tester at your service !

### ISSUE THREAD

**Issue by AugmentedRealityCat** [GeorgLegato/sd-webui-panorama-viewer#1]
I just wanted to offer my services as a beta tester. I made many panoramas with stable diffusion and this is going to be very useful to me.

You may also want to open the Discussions page on this repo to give us a space to discuss thing beyond bugs and code. 

Thanks for making this extension and sharing it with us all. It's because of people like you that Stable Diffusion is evolving so quickly !

**Comment by GeorgLegato** [comment]
hi mate, welcome
since not in public repo, you need to clone this repo into sd1111/extensions and restart sd1111
have fun

**Comment by AugmentedRealityCat** [comment]
First issue already resolved !
