### ISSUE TITLE
Cant see the tab

### ISSUE THREAD

**Issue by Tobe2d** [GeorgLegato/sd-webui-panorama-viewer#17]
Hi, I installed the extension and I cant see the tab in my Automatic1111. all I see is 2 buttons:
![image](https://user-images.githubusercontent.com/4099839/226728990-9dcd5b31-2d5f-4076-ad5d-9233fc42ee91.png)

What am I missing here?

In the log I see this:

`Panorama_Viewer: adding sendto button in parent_elem_id: txt2img_images_history_button_panel
Panorama_Viewer: adding sendto button in parent_elem_id: img2img_images_history_button_panel
Panorama_Viewer: adding sendto button in parent_elem_id: txt2img-grids_images_history_button_panel
Panorama_Viewer: adding sendto button in parent_elem_id: img2img-grids_images_history_button_panel
Panorama_Viewer: adding sendto button in parent_elem_id: Extras_images_history_button_panel
Panorama_Viewer: adding sendto button in parent_elem_id: Favorites_images_history_button_panel
Panorama_Viewer: adding sendto button in parent_elem_id: Others_images_history_button_panel
Panorama_Viewer: adding sendto button in parent_elem_id: image_buttons_ip2p`

**Comment by GeorgLegato** [comment]
Hi, I have removed the Tab, until it does not provide more function than behind he two buttons "Pano [ ]" and "Pano ( )".
Create an image, click on the gallery on it, so it is displayed in gallery as single file, now click on one of two buttons, Round or Cube-Projection
So, I got rid of one button and a redundant whole tab
