### ISSUE TITLE
my pano tab just showing video (sample) of honey bee. can't see generated image

### ISSUE THREAD

**Issue by lalamax3d** [GeorgLegato/sd-webui-panorama-viewer#26]
my extension is updated as well. am i missing something...
clicking on main pano button, opens small area below with 4 buttons...as shown 
![image](https://user-images.githubusercontent.com/567387/230819920-8429eb13-179e-4184-b6bc-c7ec427a8f34.png)

panorama viewer tab, showing video 
![image](https://user-images.githubusercontent.com/567387/230820082-29f93378-4cf1-41be-b282-99b74d35b220.png)

**Comment by GeorgLegato** [comment]
the PanoramaViewer-Tab is only to display a video. you have to create first a movie from your txt2img/img2img still.
I did that Bee-Movie using the Depth-Extension (could name now animator-depth or so).
It calculated depth map of your image and then moves that regions around, so you get the parallax feeling.

If you want to have a simple 360-sphere view click on the left most icon (the globe) so your image preview turns into 360panoramaview (without depth/animation here)

Please be aware this extension is a Viewer, so no real magic here inside. But I am adding another button Cubemap->Spherical map, so you can go for inpainting as cubemap and convert back to spherical (equirectangular) map for scaling. Cubemap has edges and on scaling you get ugly seams there. this is not happening in spherical map
