### ISSUE TITLE
Buttons not working

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [GeorgLegato/sd-webui-panorama-viewer#32]
Hi, I'm new to this extension and I wanted to try it out. However, none of the buttons work on my side:

So I click on panorama and it expands, but none of them work:

![image](https://user-images.githubusercontent.com/15929497/233148488-9e81b2f0-b6d3-4eb2-b98f-4666df406b0d.png)

![image](https://user-images.githubusercontent.com/15929497/233148406-cafa9661-e35c-49cd-a2a1-c44966b712de.png)

Thanks

**Comment by Sh4d0wHunt3rX** [comment]
By the way, I'm using Vladmandic Automatic, last version.

**Comment by GeorgLegato** [comment]
oh, the vladmandic fork is 433 commits ahead of automatic1111. so, I am afraid his repo has decent deviations.
the challenge in my extension is to be under the hood of Gradio. means a lot direct dependencie to internal representation of DOM, classes elementid... I am afraid, this wont work without forking it as well

**Comment by Sh4d0wHunt3rX** [comment]
Oh, what a pity : ( I will wait, maybe someone fork it, as I'm not developer myself. However, I suggest you to migrate to vladmandic, as it's much better and the main one seems abandoned with a lot of bugs. Thanks anyway for your extension : )

**Comment by Sh4d0wHunt3rX** [comment]
I tested on main automatic and it's not working there either, maybe I don't know how to use this extension and doing something wrong.

I'm in text 2 text, add "360 full panorama" at the start of my prompt, choose 768 x 512. Then click on panorama buttons.

Here, just the first button works, and it says panorama can't load:

![image](https://user-images.githubusercontent.com/15929497/233155649-0e296324-338b-402a-907f-22d782440757.png)

Not sure what the buttons should do at all.

The commit of this automatic is [a9eab236] , the most stable one before the major update which has a lot of bugs.

**Comment by GeorgLegato** [comment]
the buttons have tooltips, hover you mouse-
1st: open the selected image from gallery as spherical panorama
2st: same open as cubemap
3. convert current image to cubemap
4. convert cubemap to spherical image
5.

**Comment by GeorgLegato** [comment]
could you @amiremami open the dev-tools in your browser (typically F12)  and try again to open your image from gallery? make a full screenshot please. check if your image is being saved to output/samples. actually the viewer is fine with data in-browser, but I am not sure yet

**Comment by GeorgLegato** [comment]
@amiremami I ve installed Vladis1111. 
Since the extension is up and running, I ve investigated the problem. so far it is easy. the buttons do check under which Tab they are operating, and Vlad111 has rename the tab
![image](https://user-images.githubusercontent.com/7210708/233211918-d16e0cb9-cd01-4913-b9fa-866aff660c36.png)
I can fix that...

**Comment by GeorgLegato** [comment]
@amiremami please check the branch https://github.com/GeorgLegato/sd-webui-panorama-viewer/tree/Vladim1111.
so far I have fixed these feature:
 show spherical viewer
 show spherical viewer
 close viewer (x)

Todo: convert to cubemap, convert to equi
Then I could update that for good and make it public

**Comment by Sh4d0wHunt3rX** [comment]
Perfect, yes, thanks, now when I click on first button, it works and it shows me the image in panoramic style.

**Comment by GeorgLegato** [comment]
cool , next fix will be the convert buttons
