### ISSUE TITLE
Register this extension as a public visible one (on Automatic1111)

### ISSUE THREAD

**Issue by GeorgLegato** [GeorgLegato/sd-webui-panorama-viewer#7]
using the name
SD-Webui-PanoramaViewer

**Comment by ClashSAN** [comment]
viever ? what does it mean?

**Comment by GeorgLegato** [comment]
> viever ? what does it mean?

A tab in SD1111 displaying your SD-image in a mouse-interactive 3d-view

**Comment by GeorgLegato** [comment]
got into index. thx @ClashSAN
